# **1. Importación de las librerías y almacenamiento local de los archivos csv**

*   Librerías: Pandas y Requests
*   Fuente de los datos: Google Sheets (public)

Los archivos fuentes serán utilizados en tu proyecto para obtener de ellos todo lo
necesario para popular la base de datos. El proyecto deberá:
### ● Obtener los 3 archivos de fuente utilizando la librería requests y
almacenarse en forma local (Ten en cuenta que las urls pueden cambiar en
un futuro):

*   Datos Argentina - Museos
*   Datos Argentina - Salas de Cine
*   Datos Argentina - Bibliotecas Populares


### ● Organizar los archivos en rutas siguiendo la siguiente estructura:
“categoría\año-mes\categoria-dia-mes-año.csv”
* Por ejemplo: “museos\2021-noviembre\museos-03-11-2021”
* Si el archivo existe debe reemplazarse. La fecha de la nomenclatura
es la fecha de descarga.

In [126]:
import pandas as pd
import requests
r = requests.get('https://docs.google.com/spreadsheet/ccc?key=1PS2_yAvNVEuSY0gI8Nky73TQMcx_G1i18lm--jOGfAA&output=csv')
open('museos.csv', 'wb').write(r.content)
df1 = pd.read_csv('museos.csv')
df1['subcategoria'].fillna('Museos', inplace=True)
df1.head()

,Cod_Loc,IdProvincia,IdDepartamento,Observaciones,categoria,subcategoria,provincia,localidad,nombre,direccion,...,Mail,Web,Latitud,Longitud,TipoLatitudLongitud,Info_adicional,fuente,jurisdiccion,año_inauguracion,actualizacion
0,6588100,6,6588,NaN,Espacios de Exhibición Patrimonial,Museos,Buenos Aires,9 de julio,Archivo Y Museo Histórico Gral. Julio De Vedia,Libertad 1191,...,archivoymuseo@yahoo.com.ar,www.portaldel9.com.ar,-354.417.620,-608.875.980,Localización precisa,NaN,DNPyM,Municipal,1920.0,2017
1,6077010,6,6077,NaN,Espacios de Exhibición Patrimonial,Museos,Buenos Aires,Arrecifes,Museo Y Archivo Histórico De Arrecifes,Gerardo Risso y España,...,museoarrecifes@hotmail.com,NaN,-340.669.700,-601.025.550,Localización precisa,NaN,DNPyM,Municipal,1972.0,2017
2,6035010,6,6035,NaN,Espacios de Exhibición Patrimonial,Museos,Buenos Aires,Avellaneda,Museo Histórico-Sacro Hno. Rogelio Scortegagna,Calle 11 (Av. San Martín) Nº 830,...,NaN,NaN,-291.180.240,-596.545.430,Localización precisa,NaN,DNPyM,Municipal,NaN,2017
3,6035010,6,6035,NaN,Espacios de Exhibición Patrimonial,Museos,Buenos Aires,Avellaneda,Museo Municipal De Artes Plásticas De Avellaneda,"Sarmiento 101, 1 º Piso",...,NaN,NaN,-346.621.100,-583.632.700,Localización precisa,NaN,DNPyM,Municipal,1956.0,2017
4,6049020,6,6049,NaN,Espacios de Exhibición Patrimonial,Museos,Buenos Aires,Azul,Museo Etnográfico Y Archivo Histórico Enrique ...,Bartolomé J. Ronco 654,...,museoazul@yahoo.com,NaN,-367.818.240,-598.586.360,Localización precisa,NaN,DNPyM,Privada,1949.0,2017

In [127]:
df1.pivot_table(index='subcategoria', aggfunc='count', values='nombre')

              nombre
subcategoria
Museos          1182

In [128]:
r = requests.get('https://docs.google.com/spreadsheet/ccc?key=1o8QeMOKWm4VeZ9VecgnL8BWaOlX5kdCDkXoAph37sQM&output=csv')
open('cines.csv', 'wb').write(r.content)
df2 = pd.read_csv('cines.csv')
df2.head()

,Cod_Loc,IdProvincia,IdDepartamento,Observaciones,Categoría,Provincia,Departamento,Localidad,Nombre,Dirección,...,Información adicional,Latitud,Longitud,TipoLatitudLongitud,Fuente,tipo_gestion,Pantallas,Butacas,espacio_INCAA,año_actualizacion
0,10049030,10,10049,NaN,Salas de cine,Catamarca,Capital,Catamarca,Cinemacenter,Intendente Mamerto Medina 220,...,NaN,-2.846.473.700,-6.580.067.500,Localización precisa,INCAA / SInCA,Privado comercial,5,743,NaN,2018
1,10091150,10,10091,NaN,Salas de cine,Catamarca,Santa Maria,Santa María,Centro Cultural San Agustín,San Martin 173,...,NaN,-2.669.385.900,-6.604.905.800,Localización precisa,INCAA / SInCA,Privado comercial,1,440,0,2018
2,22140060,22,22140,NaN,Salas de cine,Chaco,San Fernando,Resistencia,Los Cines De La Costa,Av. Sarmiento 2600,...,NaN,-2.743.099.500,-5.896.267.200,Localización precisa,INCAA / SInCA,Privado comercial,5,820,NaN,2018
3,26091020,26,26091,NaN,Salas de cine,Chubut,Sarmiento,Sarmiento,Deborah Jones De Williams,Reg. Inf. Mec. 25 Esquina 20 De Junio,...,NaN,-4.559.437.400,-6.906.959.400,Localización precisa,INCAA / SInCA,Público municipal,1,80,NaN,2018
4,18007010,18,18007,NaN,Salas de cine,Corrientes,Bella Vista,Bella Vista,Fantasio,Salta 1059,...,NaN,-2.850.849.400,-5.904.546.400,Localización precisa,INCAA / SInCA,Privado comercial,1,240,NaN,2018

In [129]:
df2.pivot_table(index='Categoría', aggfunc='count', values='Nombre')

               Nombre
Categoría
Salas de cine     329

In [130]:
r = requests.get('https://docs.google.com/spreadsheet/ccc?key=1udwn61l_FZsFsEuU8CMVkvU2SpwPW3Krt1OML3cYMYk&output=csv')
open('biblios.csv', 'wb').write(r.content)
df3 = pd.read_csv('biblios.csv')
df3.head()

,Cod_Loc,IdProvincia,IdDepartamento,Observacion,Categoría,Subcategoria,Provincia,Departamento,Localidad,Nombre,...,Mail,Web,Información adicional,Latitud,Longitud,TipoLatitudLongitud,Fuente,Tipo_gestion,año_inicio,Año_actualizacion
0,70049060,70,70049,NaN,Bibliotecas Populares,NaN,San Juan,Iglesia,Rodeo,Biblioteca Popular Juan P. Garramuno,...,s/d,NaN,NaN,-302.092.500,-691.301.170,Localización precisa,CONABIP,Comunitaria,1930.0,2018
1,2000010,2,2000,NaN,Bibliotecas Populares,NaN,Ciudad Autónoma de Buenos Aires,Ciudad Autonoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular Helena Larroque de Roffo,...,asociacionroffo@yahoo.com.ar,NaN,NaN,-345.984.610,-584.946.900,Localización precisa,CONABIP,Comunitaria,1916.0,2018
2,2000010,2,2000,NaN,Bibliotecas Populares,NaN,Ciudad Autónoma de Buenos Aires,Ciudad Autonoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular 12 de Octubre,...,popular12deoctubre@hotmail.com,NaN,NaN,-346.132.350,-584.489.970,Localización precisa,CONABIP,Comunitaria,1910.0,2018
3,2000010,2,2000,NaN,Bibliotecas Populares,NaN,Ciudad Autónoma de Buenos Aires,Ciudad Autonoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular Villa Pueyrredón Norte,...,bibliotecapueyrredon@hotmail.com,NaN,NaN,-345.758.900,-585.015.910,Localización precisa,CONABIP,Comunitaria,1916.0,2018
4,2000010,2,2000,NaN,Bibliotecas Populares,NaN,Ciudad Autónoma de Buenos Aires,Ciudad Autonoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular Alberdi,...,bibliotecapopularalberdi@yahoo.com.ar,NaN,NaN,-345.961.570,-584.376.680,Localización precisa,CONABIP,Comunitaria,1910.0,2018

In [131]:
df3.pivot_table(index='Categoría', aggfunc='count', values='Nombre')

                       Nombre
Categoría
Bibliotecas Populares    2017

# **2. Procesamiento de los datos**

Normalizar toda la información de Museos, Salas de Cine y Bibliotecas
Populares, para crear una única tabla que contenga:
 
*   cod_localidad
*   id_provincia
*   id_departamento
*   categoría
*   provincia
*   localidad
*   nombre
*   domicilio
*   código postal
*   número de teléfono
*   mail
*   web

> ### A. Se normaliza el dataframe de museos:

In [132]:
# Se eliminan las columnas innecesarias:
df1.drop(columns=['Observaciones', 
                  'categoria', 
                  'piso', 
                  'cod_area',
                  'Latitud', 
                  'Longitud', 
                  'TipoLatitudLongitud', 
                  'Info_adicional', 
                  'fuente',
                  'jurisdiccion',
                  'año_inauguracion',
                  'actualizacion'], 
                   inplace=True)

In [133]:
# Se renombran las columnas restantes según indicaciones de normalización:
df1.rename(columns={'Cod_Loc': 'cod_localidad', 
                    'IdProvincia': 'id_provincia', 
                    'IdDepartamento': 'id_departamento',
                    'subcategoria': 'categoría', 
                    'direccion': 'domicilio', 
                    'CP': 'código postal',
                    'telefono': 'número de teléfono',
                    'Mail': 'mail',
                    'Web': 'web'}, inplace=True)

In [134]:
# Se cambian los tipos de datos del dataframe resultante:
df1 = df1.astype('string')

In [135]:
# Se cambian los valores null por el string "s/d":
df1.fillna('s/d', inplace=True)

In [136]:
df1.head()

,cod_localidad,id_provincia,id_departamento,categoría,provincia,localidad,nombre,domicilio,código postal,número de teléfono,mail,web
0,6588100,6,6588,Museos,Buenos Aires,9 de julio,Archivo Y Museo Histórico Gral. Julio De Vedia,Libertad 1191,B6500EVL,425 279,archivoymuseo@yahoo.com.ar,www.portaldel9.com.ar
1,6077010,6,6077,Museos,Buenos Aires,Arrecifes,Museo Y Archivo Histórico De Arrecifes,Gerardo Risso y España,B2740FMJ,452 931,museoarrecifes@hotmail.com,s/d
2,6035010,6,6035,Museos,Buenos Aires,Avellaneda,Museo Histórico-Sacro Hno. Rogelio Scortegagna,Calle 11 (Av. San Martín) Nº 830,S3561AKT,481 200,s/d,s/d
3,6035010,6,6035,Museos,Buenos Aires,Avellaneda,Museo Municipal De Artes Plásticas De Avellaneda,"Sarmiento 101, 1 º Piso",B1870CBC,4205 9567,s/d,s/d
4,6049020,6,6049,Museos,Buenos Aires,Azul,Museo Etnográfico Y Archivo Histórico Enrique ...,Bartolomé J. Ronco 654,B7300XAA,434 811,museoazul@yahoo.com,s/d

> ### B. Se normaliza el dataframe de cines:

In [137]:
# Se eliminan las columnas innecesarias:
df2.drop(columns=['Observaciones', 
                  'Departamento',
                  'Piso', 
                  'cod_area',
                  'Latitud', 
                  'Longitud', 
                  'TipoLatitudLongitud', 
                  'Información adicional', 
                  'Fuente',
                  'tipo_gestion',
                  'Pantallas',
                  'Butacas',
                  'espacio_INCAA',
                  'año_actualizacion'], 
                   inplace=True)

In [138]:
# Se renombran las columnas restantes según indicaciones de normalización:
df2.rename(columns={'Cod_Loc': 'cod_localidad', 
                    'IdProvincia': 'id_provincia', 
                    'IdDepartamento': 'id_departamento',
                    'Categoría': 'categoría', 
                    'Provincia': 'provincia',
                    'Localidad': 'localidad',
                    'Nombre': 'nombre',
                    'Dirección': 'domicilio', 
                    'CP': 'código postal',
                    'Teléfono': 'número de teléfono',
                    'Mail': 'mail',
                    'Web': 'web'}, inplace=True)

In [139]:
# Se cambian los tipos de datos del dataframe resultante:
df2 = df2.astype('string')

In [140]:
# Se cambian los valores null por el string "s/d":
df2.fillna('s/d', inplace=True)

In [141]:
df2.head()

,cod_localidad,id_provincia,id_departamento,categoría,provincia,localidad,nombre,domicilio,código postal,número de teléfono,mail,web
0,10049030,10,10049,Salas de cine,Catamarca,Catamarca,Cinemacenter,Intendente Mamerto Medina 220,4700,s/d,s/d,http://www.cinemacenter.com.ar/
1,10091150,10,10091,Salas de cine,Catamarca,Santa María,Centro Cultural San Agustín,San Martin 173,4139,421511,s/d,s/d
2,22140060,22,22140,Salas de cine,Chaco,Resistencia,Los Cines De La Costa,Av. Sarmiento 2600,3500,472200,administracion@loscinesdelacosta.com.ar,http://resistencia.loscinesdelacosta.com.ar/
3,26091020,26,26091,Salas de cine,Chubut,Sarmiento,Deborah Jones De Williams,Reg. Inf. Mec. 25 Esquina 20 De Junio,9020,4897169,culturasarmiento@hotmail.com,http://www.culturachubut.gob.ar/…/convo-evita-...
4,18007010,18,18007,Salas de cine,Corrientes,Bella Vista,Fantasio,Salta 1059,3432,s/d,nuevocineteatrorex@gmail.com,https://www.facebook.com/CineFantasioBellaVista/

> ### C. Se normaliza el dataframe de bibliotecas:

In [142]:
df3.dtypes

Cod_Loc                    int64
IdProvincia                int64
IdDepartamento             int64
Observacion              float64
Categoría                 object
Subcategoria             float64
Provincia                 object
Departamento              object
Localidad                 object
Nombre                    object
Domicilio                 object
Piso                     float64
CP                        object
Cod_tel                   object
Teléfono                  object
Mail                      object
Web                      float64
Información adicional    float64
Latitud                   object
Longitud                  object
TipoLatitudLongitud       object
Fuente                    object
Tipo_gestion              object
año_inicio               float64
Año_actualizacion          int64
dtype: object

In [143]:
# Se eliminan las columnas innecesarias:
df3.drop(columns=['Observacion', 
                  'Subcategoria',
                  'Departamento',
                  'Piso',
                  'Cod_tel',
                  'Latitud', 
                  'Longitud', 
                  'TipoLatitudLongitud', 
                  'Información adicional', 
                  'Fuente',
                  'Tipo_gestion',
                  'año_inicio',
                  'Año_actualizacion'], 
                   inplace=True)

In [144]:
# Se renombran las columnas restantes según indicaciones de normalización:
df3.rename(columns={'Cod_Loc': 'cod_localidad', 
                    'IdProvincia': 'id_provincia', 
                    'IdDepartamento': 'id_departamento',
                    'Categoría': 'categoría', 
                    'Provincia': 'provincia',
                    'Localidad': 'localidad',
                    'Nombre': 'nombre',
                    'Domicilio': 'domicilio', 
                    'CP': 'código postal',
                    'Teléfono': 'número de teléfono',
                    'Mail': 'mail',
                    'Web': 'web'}, inplace=True)

In [145]:
# Se cambian los tipos de datos del dataframe resultante:
df3 = df3.astype('string')

In [146]:
# Se cambian los valores null por el string "s/d":
df3.fillna('s/d', inplace=True)

In [147]:
df3.head(2)

,cod_localidad,id_provincia,id_departamento,categoría,provincia,localidad,nombre,domicilio,código postal,número de teléfono,mail,web
0,70049060,70,70049,Bibliotecas Populares,San Juan,Rodeo,Biblioteca Popular Juan P. Garramuno,Santo Domingo,5465,s/d,s/d,s/d
1,2000010,2,2000,Bibliotecas Populares,Ciudad Autónoma de Buenos Aires,Ciudad de Buenos Aires,Biblioteca Popular Helena Larroque de Roffo,Simbrón 3058,C1417EUD,45010078,asociacionroffo@yahoo.com.ar,s/d

> ### D. Se unen los tres dataframes en una única tabla:

In [148]:
frames = [df1, df2, df3]

df = pd.concat(frames, ignore_index=True)

In [149]:
df

,cod_localidad,id_provincia,id_departamento,categoría,provincia,localidad,nombre,domicilio,código postal,número de teléfono,mail,web
0,6588100,6,6588,Museos,Buenos Aires,9 de julio,Archivo Y Museo Histórico Gral. Julio De Vedia,Libertad 1191,B6500EVL,425 279,archivoymuseo@yahoo.com.ar,www.portaldel9.com.ar
1,6077010,6,6077,Museos,Buenos Aires,Arrecifes,Museo Y Archivo Histórico De Arrecifes,Gerardo Risso y España,B2740FMJ,452 931,museoarrecifes@hotmail.com,s/d
2,6035010,6,6035,Museos,Buenos Aires,Avellaneda,Museo Histórico-Sacro Hno. Rogelio Scortegagna,Calle 11 (Av. San Martín) Nº 830,S3561AKT,481 200,s/d,s/d
3,6035010,6,6035,Museos,Buenos Aires,Avellaneda,Museo Municipal De Artes Plásticas De Avellaneda,"Sarmiento 101, 1 º Piso",B1870CBC,4205 9567,s/d,s/d
4,6049020,6,6049,Museos,Buenos Aires,Azul,Museo Etnográfico Y Archivo Histórico Enrique ...,Bartolomé J. Ronco 654,B7300XAA,434 811,museoazul@yahoo.com,s/d
...,...,...,...,...,...,...,...,...,...,...,...,...
3523,62042560,62,62042,Bibliotecas Populares,Río Negro,Villa Regina,El Progreso,Pellegrini 476,8336,s/d,"helda_33@hotmail.com, bibliotecaelprogreso@hot...",s/d
3524,70028010,70,70028,Bibliotecas Populares,San Juan,"Villa Seminario, Rivadavia",Biblioteca Popular 23 de Septiembre,Pueyrredón 1692,s/d,4331521,s/d,s/d
3525,62007080,62,62007,Bibliotecas Populares,Río Negro,San Javier,Prospero Entraigas,San Javier,8500,s/d,"biblio_sanjavier@hotmail.com;, andreaaranea03@...",s/d
3526,62077010,62,62077,Bibliotecas Populares,Río Negro,Las Grutas,Cmte. Luis Piedra Buena,Villa Regina 589,8521,497263,"bibliotecalasgrutas@yahoo.com.ar, alehernandez...",s/d
3527,62042360,62,62042,Bibliotecas Populares,Río Negro,Catriel,José Hernández,Pampa Nº 691,8307,s/d,biblioteca.josehernandez.catriel@live.com,s/d

In [150]:
#Se exporta el dataframe a un nuevo archivo excel
df.to_excel('tabla única - museos_cines_bibliotecas.xlsx', 
              sheet_name='Tabla única')

> ### E. Procesar los datos conjuntos para poder generar una tabla con la siguiente información:
* Cantidad de registros totales por categoría
* Cantidad de registros totales por fuente
* Cantidad de registros por provincia y categoría

In [151]:
df_countbycat = df.pivot_table(index='categoría', aggfunc='count', values='nombre')

In [153]:
df_countbycat

                       nombre
categoría
Bibliotecas Populares    2017
Museos                   1182
Salas de cine             329